In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\python312\lib\site-packages (from pandas) (2.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gedebie abera\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\gedebie abera\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd
data1 = pd.read_csv('../data/benin-malanville.csv')
data2 = pd.read_csv('../data/togo-dapaong_qc.csv')
data3 = pd.read_csv('../data/sierraleone-bumbuna.csv')

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

print(f'THIS IS THE FIRST DATA SET: \n {df1.head()}')
print(f'THIS IS THE FIRST DATA SET: \n {df2.head()}')
print(f'THIS IS THE FIRST DATA SET: \n {df3.head()}')

In [97]:
missed1 = df1.isnull().sum()
missed2 = df2.isnull().sum()
missed3 = df3.isnull().sum()
print(f'This is the missed values: \n{missed1}')
print(f'This is the missed values: \n{missed2}')
print(f'This is the missed values: \n{missed3}')

This is the missed values:
Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64
This is the missed values:
Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64
This is the missed values:
Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64

In [39]:
df1_duplicated = df1[df1.duplicated]
df2_duplicated = df2[df2.duplicated]
df3_duplicated = df3[df3.duplicated]
print(len(df1_duplicated))
print(len(df2_duplicated))
print(len(df3_duplicated))

0
0
0

In [60]:
df1['Comments'] = df1['Comments'].fillna(0)
df2['Comments'] = df2['Comments'].fillna(0)
df3['Comments'] = df3['Comments'].fillna(0)
print(df1['Comments'].head())
print(df2['Comments'].head())
print(df3['Comments'].head())

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Comments, dtype: float64
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Comments, dtype: float64
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Comments, dtype: float64

In [108]:
print("SUMMARY STATISTICS")

SUMMARY STATISTICS

In [94]:
headers1 = df1.columns
headers2 = df2.columns
headers3 = df3.columns

def mean1():
    for header1 in headers1:
        if pd.api.types.is_numeric_dtype(df1[header1]):
            mean_value = df1[header1].mean()
            print(f'Mean of {header1}: {mean_value}')
        else:
            print(f'{header1} is not a numeric column.')

def mean2():
    for header2 in headers2:
        if pd.api.types.is_numeric_dtype(df2[header2]):
            mean_value = df2[header2].mean()
            print(f'Mean of {header2}: {mean_value}')
        else:
            print(f'{header2} is not a numeric column.')


def mean3():
    for header3 in headers3:
        if pd.api.types.is_numeric_dtype(df3[header3]):
            mean_value = df3[header3].mean()
            print(f'Mean of {header3}: {mean_value}')
        else:
            print(f'{header3} is not a numeric column.')
print(f'{mean1()} {mean2()} {mean3()}')

Timestamp is not a numeric column.
Mean of GHI: 241.95882077625572
Mean of DNI: 167.44186624809745
Mean of DHI: 116.99303348554032
Mean of ModA: 236.5894961948249
Mean of ModB: 228.883575913242
Mean of Tamb: 28.179682838660575
Mean of RH: 54.4879691780822
Mean of WS: 2.121112823439878
Mean of WSgust: 2.8091948249619483
Mean of WSstdev: 0.4733896499238964
Mean of WD: 153.43517199391172
Mean of WDstdev: 8.582406582952814
Mean of BP: 994.197199391172
Mean of Cleaning: 0.0009227549467275495
Mean of Precipitation: 0.001904870624048706
Mean of TModA: 35.2460256849315
Mean of TModB: 32.47173554033485
Mean of Comments: 0.0
Timestamp is not a numeric column.
Mean of GHI: 231.71878576864535
Mean of DNI: 151.25846898782348
Mean of DHI: 116.44435235920854
Mean of ModA: 226.14437461948242
Mean of ModB: 219.56858808980218
Mean of Tamb: 27.75178805175039
Mean of RH: 55.01315981735161
Mean of WS: 2.3680934170471843
Mean of WSgust: 3.2294895357686455
Mean of WSstdev: 0.5577395357686454
Mean of WD: 161.74184531963462
Mean of WDstdev: 10.559568493150685
Mean of BP: 975.9152416286149
Mean of Cleaning: 0.0005346270928462709
Mean of Precipitation: 0.001382039573820396
Mean of TModA: 32.44440296803653
Mean of TModB: 33.54332971841705
Mean of Comments: 0.0
Timestamp is not a numeric column.
Mean of GHI: 204.40677796803655
Mean of DNI: 116.52373078386607
Mean of DHI: 116.27367713089801
Mean of ModA: 206.6430951293759
Mean of ModB: 198.11469121004558
Mean of Tamb: 26.319394216133944
Mean of RH: 79.44885730593609
Mean of WS: 1.1461130136986302
Mean of WSgust: 1.6916059741248095
Mean of WSstdev: 0.36382286910197875
Mean of WD: 133.0446683789954
Mean of WDstdev: 7.1722197488584465
Mean of BP: 999.8764687975647
Mean of Cleaning: 0.0009665144596651446
Mean of Precipitation: 0.00480593607305936
Mean of TModA: 32.504263127853875
Mean of TModB: 32.5930905631659
Mean of Comments: 0.0
None None None

In [61]:
headers1 = df1.columns
headers2 = df2.columns
headers3 = df3.columns

def median1():
    for header1 in headers1:
        if pd.api.types.is_numeric_dtype(df1[header1]):
            median_value = df1[header1].median()
            print(f'Median of {header1}: {median_value}')
        else:
            print(f'{header1} is not a numeric column.')

def median2():
    for header2 in headers2:
        if pd.api.types.is_numeric_dtype(df2[header2]):
            median_value = df2[header2].median()
            print(f'median of {header2}: {median_value}')
        else:
            print(f'{header2} is not a numeric column.')


def median3():
    for header3 in headers3:
        if pd.api.types.is_numeric_dtype(df3[header3]):
            median_value = df3[header3].median()
            print(f'median of {header3}: {median_value}')
        else:
            print(f'{header3} is not a numeric column.')
print(f'{median1()} {median2()} {median3()}')

Timestamp is not a numeric column.
Median of GHI: 1.8
Median of DNI: -0.1
Median of DHI: 1.6
Median of ModA: 4.5
Median of ModB: 4.3
Median of Tamb: 28.0
Median of RH: 55.1
Median of WS: 1.9
Median of WSgust: 2.6
Median of WSstdev: 0.5
Median of WD: 181.0
Median of WDstdev: 8.6
Median of BP: 994.0
Median of Cleaning: 0.0
Median of Precipitation: 0.0
Median of TModA: 30.0
Median of TModB: 28.9
Median of Comments: 0.0
Timestamp is not a numeric column.
median of GHI: 2.1
median of DNI: 0.0
median of DHI: 2.5
median of ModA: 4.4
median of ModB: 4.3
median of Tamb: 27.2
median of RH: 59.3
median of WS: 2.2
median of WSgust: 2.9
median of WSstdev: 0.5
median of WD: 199.1
median of WDstdev: 10.8
median of BP: 976.0
median of Cleaning: 0.0
median of Precipitation: 0.0
median of TModA: 28.4
median of TModB: 28.4
median of Comments: 0.0
Timestamp is not a numeric column.
median of GHI: 0.3
median of DNI: -0.1
median of DHI: -0.1
median of ModA: 3.6
median of ModB: 3.4
median of Tamb: 25.3
median of RH: 85.4
median of WS: 0.8
median of WSgust: 1.6
median of WSstdev: 0.4
median of WD: 161.5
median of WDstdev: 6.2
median of BP: 1000.0
median of Cleaning: 0.0
median of Precipitation: 0.0
median of TModA: 26.6
median of TModB: 26.9
median of Comments: 0.0
None None None

In [93]:
headers1 = df1.columns
headers2 = df2.columns
headers3 = df3.columns

def std1():
    for header1 in headers1:
        if pd.api.types.is_numeric_dtype(df1[header1]):
            std_value = df1[header1].std()
            print(f'Standard divation of {header1}: {std_value}')
        else:
            print(f'{header1} is not a numeric column.')

def std2():
    for header2 in headers2:
        if pd.api.types.is_numeric_dtype(df2[header2]):
            std_value = df2[header2].std()
            print(f'Standard divation of {header2}: {std_value}')
        else:
            print(f'{header2} is not a numeric column.')


def std3():
    for header3 in headers3:
        if pd.api.types.is_numeric_dtype(df3[header3]):
            std_value = df3[header3].std()
            print(f'Standard divation of {header3}: {std_value}')
        else:
            print(f'{header3} is not a numeric column.')
print(f'{std1()} {std2()} {std3()}')

Timestamp is not a numeric column.
Standard divation of GHI: 330.10178719473936
Standard divation of DNI: 261.5475324834319
Standard divation of DHI: 157.46361880833496
Standard divation of ModA: 326.89485851507413
Standard divation of ModB: 316.53651537980164
Standard divation of Tamb: 5.924296981332788
Standard divation of RH: 28.073068781205844
Standard divation of WS: 1.6034658845357102
Standard divation of WSgust: 2.029119651774774
Standard divation of WSstdev: 0.2733946213736333
Standard divation of WD: 102.33284204706163
Standard divation of WDstdev: 6.385864053158973
Standard divation of BP: 2.474993197988568
Standard divation of Cleaning: 0.030362892221282408
Standard divation of Precipitation: 0.03711520540633969
Standard divation of TModA: 14.807257528633412
Standard divation of TModB: 12.348743384105228
Standard divation of Comments: 0.0
Timestamp is not a numeric column.
Standard divation of GHI: 321.6919532125897
Standard divation of DNI: 250.9569616573671
Standard divation of DHI: 156.52071366117195
Standard divation of ModA: 317.3469382524454
Standard divation of ModB: 307.9325104175355
Standard divation of Tamb: 4.758022740618851
Standard divation of RH: 28.778732322296694
Standard divation of WS: 1.462667670344068
Standard divation of WSgust: 1.882564525208805
Standard divation of WSstdev: 0.268923061732855
Standard divation of WD: 91.87721656228369
Standard divation of WDstdev: 5.915489536764592
Standard divation of BP: 2.153977480335337
Standard divation of Cleaning: 0.023115844854792233
Standard divation of Precipitation: 0.02635003158140825
Standard divation of TModA: 10.99833354593578
Standard divation of TModB: 12.76927711913104
Standard divation of Comments: 0.0
Timestamp is not a numeric column.
Standard divation of GHI: 296.7875199493238
Standard divation of DNI: 218.57399206825494
Standard divation of DHI: 157.02086824840762
Standard divation of ModA: 300.8968926212413
Standard divation of ModB: 288.8890726857755
Standard divation of Tamb: 4.398605011595131
Standard divation of RH: 20.520774562690175
Standard divation of WS: 1.2392483687506368
Standard divation of WSgust: 1.617053354438623
Standard divation of WSstdev: 0.29500006363719533
Standard divation of WD: 114.28479181237655
Standard divation of WDstdev: 7.5350931592808434
Standard divation of BP: 2.104419226069219
Standard divation of Cleaning: 0.031073817701868293
Standard divation of Precipitation: 0.047555992534041275
Standard divation of TModA: 12.434898577542754
Standard divation of TModB: 12.009161313594923
Standard divation of Comments: 0.0
None None None

In [92]:
headers1 = df1.columns
headers2 = df2.columns
headers3 = df3.columns

def var1():
    for header1 in headers1:
        if pd.api.types.is_numeric_dtype(df1[header1]):
            var_value = df1[header1].var()
            print(f'var of {header1}: {var_value}')
        else:
            print(f'{header1} is not a numeric column.')

def var2():
    for header2 in headers2:
        if pd.api.types.is_numeric_dtype(df2[header2]):
            var_value = df2[header2].var()
            print(f'var of {header2}: {var_value}')
        else:
            print(f'{header2} is not a numeric column.')


def var3():
    for header3 in headers3:
        if pd.api.types.is_numeric_dtype(df3[header3]):
            var_value = df3[header3].var()
            print(f'var of {header3}: {var_value}')
        else:
            print(f'{header3} is not a numeric column.')
print(f'{var1()} {var2()} {var3()}')

Timestamp is not a numeric column.
var of GHI: 108967.189909161
var of DNI: 68407.11174817187
var of DHI: 24794.791248216618
var of ModA: 106860.24852359034
var of ModB: 100195.36556878741
var of Tamb: 35.09729472302879
var of RH: 788.0971907943142
var of WS: 2.5711028428698874
var of WSgust: 4.117326561218579
var of WSstdev: 0.0747446189960323
var of WD: 10472.010561428866
var of WDstdev: 40.77925970542795
var of BP: 6.125591330089681
var of Cleaning: 0.0009219052240412117
var of Precipitation: 0.0013775384723547868
var of TModA: 219.25487551927088
var of TModB: 152.49146316648265
var of Comments: 0.0
Timestamp is not a numeric column.
var of GHI: 103485.712761731
var of DNI: 62979.39660429721
var of DHI: 24498.73380500258
var of ModA: 100709.0792182014
var of ModB: 94822.43097204564
var of Tamb: 22.638780400246127
var of RH: 828.2154340784045
var of WS: 2.139396713869743
var of WSgust: 3.5440491915746537
var of WSstdev: 0.07231961313177294
var of WD: 8441.422923232778
var of WDstdev: 34.993016459571365
var of BP: 4.639618985791768
var of Cleaning: 0.0005343422833508246
var of Precipitation: 0.0006943241643412123
var of TModA: 120.96334078765634
var of TModB: 163.05443814516352
var of Comments: 0.0
Timestamp is not a numeric column.
var of GHI: 88082.83199767028
var of DNI: 47774.59000865357
var of DHI: 24655.553065483782
var of ModA: 90538.93998911881
var of ModB: 83456.89631724729
var of Tamb: 19.3477260480298
var of RH: 421.1021886527521
var of WS: 1.5357365194511146
var of WSgust: 2.6148615511012028
var of WSstdev: 0.08702503754594929
var of WD: 13061.01363959825
var of WDstdev: 56.777628919040964
var of BP: 4.428580279049771
var of Cleaning: 0.0009655821465689433
var of Precipitation: 0.002261572425897789
var of TModA: 154.62670263377478
var of TModB: 144.21995545594496
var of Comments: 0.0
None None None

In [70]:
negative_values = (df3[['GHI', 'DNI', 'DHI']] < 0).sum()
print(negative_values)

GHI    261135
DNI    266352
DHI    263128
dtype: int64

In [91]:
df1['GHI'] = df1['GHI'].map(lambda x: x if x >= 0 else 0)
df1['DNI'] = df1['DNI'].map(lambda x: x if x >= 0 else 0)
df1['DHI'] = df1['DHI'].map(lambda x: x if x >= 0 else 0)

print(df1[['GHI', 'DNI', 'DHI']].head())

df2['GHI'] = df2['GHI'].map(lambda x: x if x >= 0 else 0)
df2['DNI'] = df2['DNI'].map(lambda x: x if x >= 0 else 0)
df2['DHI'] = df2['DHI'].map(lambda x: x if x >= 0 else 0)

print(df2[['GHI', 'DNI', 'DHI']].head())

df3['GHI'] = df3['GHI'].map(lambda x: x if x >= 0 else 0)
df3['DNI'] = df3['DNI'].map(lambda x: x if x >= 0 else 0)
df3['DHI'] = df3['DHI'].map(lambda x: x if x >= 0 else 0)

print(df3[['GHI', 'DNI', 'DHI']].head())

   GHI  DNI  DHI
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  0.0  0.0
4  0.0  0.0  0.0
   GHI  DNI  DHI
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  0.0  0.0
4  0.0  0.0  0.0
   GHI  DNI  DHI
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  0.0  0.0
4  0.0  0.0  0.0

In [79]:
negative_values1 = (df1[['GHI', 'DNI', 'DHI']] < 0).sum()
negative_values2 = (df2[['GHI', 'DNI', 'DHI']] < 0).sum()
negative_values3 = (df3[['GHI', 'DNI', 'DHI']] < 0).sum()
print(negative_values1)

GHI    0
DNI    0
DHI    0
dtype: int64

In [105]:
print("DATA QUALITY CHECK")

Data Quality Check

In [ ]:
def detect_outliers_iqr(column):
    Q1 = df1[column].quantile(0.25)
    Q3 = df1[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df1[(df1[column] < lower_bound) | (df1[column] > upper_bound)]

outliers_modA = detect_outliers_iqr('ModA')
outliers_modB = detect_outliers_iqr('ModB')
print("Outliers in ModA:\n", outliers_modA)
print("Outliers in ModB:\n", outliers_modB)
print("Outliers in WS:\n", outliers_ws)
print("Outliers in WSgust:\n", outliers_wsgust)

In [ ]:
def detect_outliers_iqr(column):
    Q1 = df2[column].quantile(0.25)
    Q3 = df2[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df2[(df2[column] < lower_bound) | (df2[column] > upper_bound)]

outliers_modA = detect_outliers_iqr('ModA')
outliers_modB = detect_outliers_iqr('ModB')
print("Outliers in ModA:\n", outliers_modA)
print("Outliers in ModB:\n", outliers_modB)
print("Outliers in WS:\n", outliers_ws)
print("Outliers in WSgust:\n", outliers_wsgust)

In [107]:
def detect_outliers_iqr(column):
    Q1 = df3[column].quantile(0.25)
    Q3 = df3[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df3[(df3[column] < lower_bound) | (df3[column] > upper_bound)]

outliers_modA = detect_outliers_iqr('ModA')
outliers_modB = detect_outliers_iqr('ModB')
print("Outliers in ModA:\n", outliers_modA)
print("Outliers in ModB:\n", outliers_modB)
print("Outliers in WS:\n", outliers_ws)
print("Outliers in WSgust:\n", outliers_wsgust)

Outliers in ModA:
                Timestamp    GHI    DNI    DHI    ModA    ModB  Tamb    RH  \
655     2021-10-30 10:56  851.0  285.0  605.9   912.0   890.0  26.0  84.2
658     2021-10-30 10:59  932.0  397.7  589.4  1002.0   978.0  26.2  85.6
659     2021-10-30 11:00  995.0  492.6  571.1  1065.0  1039.0  26.4  83.4
660     2021-10-30 11:01  988.0  504.2  552.7  1050.0  1025.0  26.5  83.6
661     2021-10-30 11:02  978.0  506.0  541.7  1049.0  1025.0  26.4  82.7
...                  ...    ...    ...    ...     ...     ...   ...   ...
524844  2022-10-29 11:25  888.0  362.7  559.4   932.0   910.0  30.6  77.0
524845  2022-10-29 11:26  986.0  474.4  556.7  1035.0  1009.0  30.7  76.0
524862  2022-10-29 11:43  928.0  400.5  556.8   974.0   949.0  30.0  76.4
524863  2022-10-29 11:44  925.0  396.3  556.9   972.0   946.0  30.2  76.2
524864  2022-10-29 11:45  905.0  385.8  547.0   952.0   927.0  30.3  77.0

         WS  WSgust  WSstdev     WD  WDstdev    BP  Cleaning  Precipitation  \
655     1.6     2.1      0.5   66.4     14.6  1002         0            0.0
658     1.7     2.4      0.5  121.7     12.1  1002         0            0.0
659     1.6     2.1      0.4   98.3     16.3  1002         0            0.0
660     1.5     2.4      0.5   49.9     11.9  1002         0            0.0
661     0.4     1.4      0.6   29.4      7.3  1002         0            0.0
...     ...     ...      ...    ...      ...   ...       ...            ...
524844  0.7     1.9      0.7  276.6      5.3  1001         0            0.0
524845  0.2     1.1      0.4   34.4      3.5  1001         0            0.0
524862  0.0     0.4      0.1  338.2      0.0  1000         0            0.0
524863  0.3     1.1      0.5  355.3      4.7  1000         0            0.0
524864  0.1     0.7      0.3  297.3      0.0  1000         0            0.0

        TModA  TModB  Comments
655      52.4   47.0       NaN
658      55.5   49.4       NaN
659      56.3   49.7       NaN
660      57.1   50.0       NaN
661      57.8   50.4       NaN
...       ...    ...       ...
524844   58.5   56.2       NaN
524845   59.2   57.0       NaN
524862   51.0   49.9       NaN
524863   53.3   51.8       NaN
524864   55.2   53.3       NaN

[21017 rows x 19 columns]
Outliers in ModB:
                Timestamp    GHI    DNI    DHI    ModA    ModB  Tamb    RH  \
655     2021-10-30 10:56  851.0  285.0  605.9   912.0   890.0  26.0  84.2
658     2021-10-30 10:59  932.0  397.7  589.4  1002.0   978.0  26.2  85.6
659     2021-10-30 11:00  995.0  492.6  571.1  1065.0  1039.0  26.4  83.4
660     2021-10-30 11:01  988.0  504.2  552.7  1050.0  1025.0  26.5  83.6
661     2021-10-30 11:02  978.0  506.0  541.7  1049.0  1025.0  26.4  82.7
...                  ...    ...    ...    ...     ...     ...   ...   ...
524844  2022-10-29 11:25  888.0  362.7  559.4   932.0   910.0  30.6  77.0
524845  2022-10-29 11:26  986.0  474.4  556.7  1035.0  1009.0  30.7  76.0
524862  2022-10-29 11:43  928.0  400.5  556.8   974.0   949.0  30.0  76.4
524863  2022-10-29 11:44  925.0  396.3  556.9   972.0   946.0  30.2  76.2
524864  2022-10-29 11:45  905.0  385.8  547.0   952.0   927.0  30.3  77.0

         WS  WSgust  WSstdev     WD  WDstdev    BP  Cleaning  Precipitation  \
655     1.6     2.1      0.5   66.4     14.6  1002         0            0.0
658     1.7     2.4      0.5  121.7     12.1  1002         0            0.0
659     1.6     2.1      0.4   98.3     16.3  1002         0            0.0
660     1.5     2.4      0.5   49.9     11.9  1002         0            0.0
661     0.4     1.4      0.6   29.4      7.3  1002         0            0.0
...     ...     ...      ...    ...      ...   ...       ...            ...
524844  0.7     1.9      0.7  276.6      5.3  1001         0            0.0
524845  0.2     1.1      0.4   34.4      3.5  1001         0            0.0
524862  0.0     0.4      0.1  338.2      0.0  1000         0            0.0
524863  0.3     1.1      0.5  355.3      4.7  1000         0            0.0
524864  0.1     0.7      0.3  297.3      0.0  1000         0            0.0

        TModA  TModB  Comments
655      52.4   47.0       NaN
658      55.5   49.4       NaN
659      56.3   49.7       NaN
660      57.1   50.0       NaN
661      57.8   50.4       NaN
...       ...    ...       ...
524844   58.5   56.2       NaN
524845   59.2   57.0       NaN
524862   51.0   49.9       NaN
524863   53.3   51.8       NaN
524864   55.2   53.3       NaN

[20613 rows x 19 columns]
Outliers in WS:
                Timestamp    GHI  DNI    DHI   ModA   ModB  Tamb    RH   WS  \
2209    2021-08-10 12:50  360.2  0.7  359.9  339.9  344.2  31.6  63.0  6.4
2879    2021-08-11 00:00    0.0  0.0    0.0    0.0    0.0  24.7  93.7  6.9
2950    2021-08-11 01:11    0.0  0.0    0.0    0.0    0.0  23.9  96.2  6.6
2957    2021-08-11 01:18    0.0  0.0    0.0    0.0    0.0  23.5  95.6  6.4
2958    2021-08-11 01:19    0.0  0.0    0.0    0.0    0.0  23.5  94.9  7.9
...                  ...    ...  ...    ...    ...    ...   ...   ...  ...
525151  2022-08-08 16:32    4.7  0.0    4.8    6.0    5.9  22.0  99.1  7.3
525152  2022-08-08 16:33    4.8  0.1    4.9    6.0    5.9  22.0  99.1  6.3
525155  2022-08-08 16:36    4.8  0.0    4.9    6.0    5.9  22.0  99.1  6.9
525156  2022-08-08 16:37    4.9  0.0    5.0    6.0    5.9  22.0  99.1  6.5
525159  2022-08-08 16:40    4.9  0.0    5.0    5.9    5.7  22.1  99.2  6.3

        WSgust  WSstdev     WD  WDstdev   BP  Cleaning  Precipitation  TModA  \
2209       7.7      0.9  241.6     10.8  997         0            0.0   47.0
2879       8.4      0.9   48.4      7.6  996         0            0.4   25.5
2950       8.4      1.1  246.1      9.8  996         0            0.0   24.7
2957       8.7      1.4  250.7      9.5  996         0            0.0   24.3
2958       9.4      0.8  244.3      8.1  996         0            0.0   24.3
...        ...      ...    ...      ...  ...       ...            ...    ...
525151     8.7      0.8  146.9      8.8  995         0            0.1   22.8
525152     8.2      1.0  152.1     10.0  995         0            0.1   22.7
525155     8.9      1.1  153.8      9.4  995         0            0.1   22.8
525156     8.2      0.9  152.3      8.9  995         0            0.0   22.8
525159     8.4      1.2  155.2      7.1  994         0            0.1   22.8

        TModB  Comments
2209     44.8       NaN
2879     24.9       NaN
2950     24.2       NaN
2957     23.8       NaN
2958     23.7       NaN
...       ...       ...
525151   22.0       NaN
525152   22.0       NaN
525155   22.0       NaN
525156   22.0       NaN
525159   22.1       NaN

[6717 rows x 19 columns]
Outliers in WSgust:
                Timestamp  GHI  DNI  DHI  ModA  ModB  Tamb    RH   WS  WSgust  \
2876    2021-08-10 23:57  0.0  0.0  0.0   0.0   0.0  25.3  91.5  5.6     8.4
2879    2021-08-11 00:00  0.0  0.0  0.0   0.0   0.0  24.7  93.7  6.9     8.4
2950    2021-08-11 01:11  0.0  0.0  0.0   0.0   0.0  23.9  96.2  6.6     8.4
2957    2021-08-11 01:18  0.0  0.0  0.0   0.0   0.0  23.5  95.6  6.4     8.7
2958    2021-08-11 01:19  0.0  0.0  0.0   0.0   0.0  23.5  94.9  7.9     9.4
...                  ...  ...  ...  ...   ...   ...   ...   ...  ...     ...
525143  2022-08-08 16:24  4.5  0.0  4.5   5.8   5.7  21.9  99.0  6.7     8.9
525150  2022-08-08 16:31  4.7  0.0  4.8   5.9   5.8  22.0  99.1  6.7     8.4
525151  2022-08-08 16:32  4.7  0.0  4.8   6.0   5.9  22.0  99.1  7.3     8.7
525155  2022-08-08 16:36  4.8  0.0  4.9   6.0   5.9  22.0  99.1  6.9     8.9
525159  2022-08-08 16:40  4.9  0.0  5.0   5.9   5.7  22.1  99.2  6.3     8.4

        WSstdev     WD  WDstdev   BP  Cleaning  Precipitation  TModA  TModB  \
2876        1.3   50.2     11.5  996         0            0.0   25.9   25.5
2879        0.9   48.4      7.6  996         0            0.4   25.5   24.9
2950        1.1  246.1      9.8  996         0            0.0   24.7   24.2
2957        1.4  250.7      9.5  996         0            0.0   24.3   23.8
2958        0.8  244.3      8.1  996         0            0.0   24.3   23.7
...         ...    ...      ...  ...       ...            ...    ...    ...
525143      1.1  132.0      8.1  995         0            0.2   22.7   22.0
525150      1.2  139.3     12.7  995         0            0.2   22.8   22.0
525151      0.8  146.9      8.8  995         0            0.1   22.8   22.0
525155      1.1  153.8      9.4  995         0            0.1   22.8   22.0
525159      1.2  155.2      7.1  994         0            0.1   22.8   22.1

        Comments
2876         NaN
2879         NaN
2950         NaN
2957         NaN
2958         NaN
...          ...
525143       NaN
525150       NaN
525151       NaN
525155       NaN
525159       NaN

[5368 rows x 19 columns]