In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\python312\lib\site-packages (from pandas) (2.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gedebie abera\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\gedebie abera\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [35]:
import pandas as pd
data1 = pd.read_csv('../data/benin-malanville.csv')
data2 = pd.read_csv('../data/togo-dapaong_qc.csv')
data3 = pd.read_csv('../data/sierraleone-bumbuna.csv')

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

print(f'THIS IS THE FIRST DATA SET: \n {df1.head()}')
print(f'THIS IS THE FIRST DATA SET: \n {df2.head()}')
print(f'THIS IS THE FIRST DATA SET: \n {df3.head()}')

THIS IS THE FIRST DATA SET:
           Timestamp  GHI  DNI  DHI  ModA  ModB  Tamb    RH   WS  WSgust  \
0  2021-08-09 00:01 -1.2 -0.2 -1.1   0.0   0.0  26.2  93.4  0.0     0.4
1  2021-08-09 00:02 -1.1 -0.2 -1.1   0.0   0.0  26.2  93.6  0.0     0.0
2  2021-08-09 00:03 -1.1 -0.2 -1.1   0.0   0.0  26.2  93.7  0.3     1.1
3  2021-08-09 00:04 -1.1 -0.1 -1.0   0.0   0.0  26.2  93.3  0.2     0.7
4  2021-08-09 00:05 -1.0 -0.1 -1.0   0.0   0.0  26.2  93.3  0.1     0.7

   WSstdev     WD  WDstdev   BP  Cleaning  Precipitation  TModA  TModB  \
0      0.1  122.1      0.0  998         0            0.0   26.3   26.2
1      0.0    0.0      0.0  998         0            0.0   26.3   26.2
2      0.5  124.6      1.5  997         0            0.0   26.4   26.2
3      0.4  120.3      1.3  997         0            0.0   26.4   26.3
4      0.3  113.2      1.0  997         0            0.0   26.4   26.3

   Comments
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
THIS IS THE FIRST DATA SET:
           Timestamp  GHI  DNI  DHI  ModA  ModB  Tamb    RH   WS  WSgust  \
0  2021-10-25 00:01 -1.3  0.0  0.0   0.0   0.0  24.8  94.5  0.9     1.1
1  2021-10-25 00:02 -1.3  0.0  0.0   0.0   0.0  24.8  94.4  1.1     1.6
2  2021-10-25 00:03 -1.3  0.0  0.0   0.0   0.0  24.8  94.4  1.2     1.4
3  2021-10-25 00:04 -1.2  0.0  0.0   0.0   0.0  24.8  94.3  1.2     1.6
4  2021-10-25 00:05 -1.2  0.0  0.0   0.0   0.0  24.8  94.0  1.3     1.6

   WSstdev     WD  WDstdev   BP  Cleaning  Precipitation  TModA  TModB  \
0      0.4  227.6      1.1  977         0            0.0   24.7   24.4
1      0.4  229.3      0.7  977         0            0.0   24.7   24.4
2      0.3  228.5      2.9  977         0            0.0   24.7   24.4
3      0.3  229.1      4.6  977         0            0.0   24.7   24.4
4      0.4  227.5      1.6  977         0            0.0   24.7   24.4

   Comments
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
THIS IS THE FIRST DATA SET:
           Timestamp  GHI  DNI  DHI  ModA  ModB  Tamb    RH   WS  WSgust  \
0  2021-10-30 00:01 -0.7 -0.1 -0.8   0.0   0.0  21.9  99.1  0.0     0.0
1  2021-10-30 00:02 -0.7 -0.1 -0.8   0.0   0.0  21.9  99.2  0.0     0.0
2  2021-10-30 00:03 -0.7 -0.1 -0.8   0.0   0.0  21.9  99.2  0.0     0.0
3  2021-10-30 00:04 -0.7  0.0 -0.8   0.0   0.0  21.9  99.3  0.0     0.0
4  2021-10-30 00:05 -0.7 -0.1 -0.8   0.0   0.0  21.9  99.3  0.0     0.0

   WSstdev   WD  WDstdev    BP  Cleaning  Precipitation  TModA  TModB  \
0      0.0  0.0      0.0  1002         0            0.0   22.3   22.6
1      0.0  0.0      0.0  1002         0            0.0   22.3   22.6
2      0.0  0.0      0.0  1002         0            0.0   22.3   22.6
3      0.0  0.0      0.0  1002         0            0.1   22.3   22.6
4      0.0  0.0      0.0  1002         0            0.0   22.3   22.6

   Comments
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN

In [36]:
missed1 = df1.isnull().sum()
missed2 = df2.isnull().sum()
missed3 = df3.isnull().sum()
print(f'This is the missed values: \n{missed1}')
print(f'This is the missed values: \n{missed2}')
print(f'This is the missed values: \n{missed3}')

This is the missed values:
Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64
This is the missed values:
Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64
This is the missed values:
Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64

In [39]:
df1_duplicated = df1[df1.duplicated]
df2_duplicated = df2[df2.duplicated]
df3_duplicated = df3[df3.duplicated]
print(len(df1_duplicated))
print(len(df2_duplicated))
print(len(df3_duplicated))

0
0
0

In [60]:
df1['Comments'] = df1['Comments'].fillna(0)
df2['Comments'] = df2['Comments'].fillna(0)
df3['Comments'] = df3['Comments'].fillna(0)
print(df1['Comments'].head())
print(df2['Comments'].head())
print(df3['Comments'].head())

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Comments, dtype: float64
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Comments, dtype: float64
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Comments, dtype: float64

In [53]:
headers1 = df1.columns
headers2 = df2.columns
headers3 = df3.columns

def mean1():
    for header1 in headers1:
        if pd.api.types.is_numeric_dtype(df1[header1]):
            mean_value = df1[header1].mean()
            print(f'Mean of {header1}: {mean_value}')
        else:
            print(f'{header1} is not a numeric column.')

def mean2():
    for header2 in headers2:
        if pd.api.types.is_numeric_dtype(df2[header2]):
            mean_value = df2[header2].mean()
            print(f'Mean of {header2}: {mean_value}')
        else:
            print(f'{header2} is not a numeric column.')


def mean3():
    for header3 in headers3:
        if pd.api.types.is_numeric_dtype(df3[header3]):
            mean_value = df3[header3].mean()
            print(f'Mean of {header3}: {mean_value}')
        else:
            print(f'{header3} is not a numeric column.')
print(f'{mean1()} {mean2()} {mean3()}')

Timestamp is not a numeric column.
Mean of GHI: 240.559452435312
Mean of DNI: 167.18751598173515
Mean of DHI: 115.35896080669708
Mean of ModA: 236.5894961948249
Mean of ModB: 228.883575913242
Mean of Tamb: 28.179682838660575
Mean of RH: 54.4879691780822
Mean of WS: 2.121112823439878
Mean of WSgust: 2.8091948249619483
Mean of WSstdev: 0.4733896499238964
Mean of WD: 153.43517199391172
Mean of WDstdev: 8.582406582952814
Mean of BP: 994.197199391172
Mean of Cleaning: 0.0009227549467275495
Mean of Precipitation: 0.001904870624048706
Mean of TModA: 35.2460256849315
Mean of TModB: 32.47173554033485
Mean of Comments: 0.0
Timestamp is not a numeric column.
Mean of GHI: 230.55503976407917
Mean of DNI: 151.25846898782348
Mean of DHI: 116.44435235920854
Mean of ModA: 226.14437461948242
Mean of ModB: 219.56858808980218
Mean of Tamb: 27.75178805175039
Mean of RH: 55.01315981735161
Mean of WS: 2.3680934170471843
Mean of WSgust: 3.2294895357686455
Mean of WSstdev: 0.5577395357686454
Mean of WD: 161.74184531963462
Mean of WDstdev: 10.559568493150685
Mean of BP: 975.9152416286149
Mean of Cleaning: 0.0005346270928462709
Mean of Precipitation: 0.001382039573820396
Mean of TModA: 32.44440296803653
Mean of TModB: 33.54332971841705
Mean of Comments: nan
Timestamp is not a numeric column.
Mean of GHI: 201.95751522070017
Mean of DNI: 116.37633694824962
Mean of DHI: 113.720570585997
Mean of ModA: 206.6430951293759
Mean of ModB: 198.11469121004558
Mean of Tamb: 26.319394216133944
Mean of RH: 79.44885730593609
Mean of WS: 1.1461130136986302
Mean of WSgust: 1.6916059741248095
Mean of WSstdev: 0.36382286910197875
Mean of WD: 133.0446683789954
Mean of WDstdev: 7.1722197488584465
Mean of BP: 999.8764687975647
Mean of Cleaning: 0.0009665144596651446
Mean of Precipitation: 0.00480593607305936
Mean of TModA: 32.504263127853875
Mean of TModB: 32.5930905631659
Mean of Comments: nan
None None None

In [61]:
headers1 = df1.columns
headers2 = df2.columns
headers3 = df3.columns

def median1():
    for header1 in headers1:
        if pd.api.types.is_numeric_dtype(df1[header1]):
            median_value = df1[header1].median()
            print(f'Median of {header1}: {median_value}')
        else:
            print(f'{header1} is not a numeric column.')

def median2():
    for header2 in headers2:
        if pd.api.types.is_numeric_dtype(df2[header2]):
            median_value = df2[header2].median()
            print(f'median of {header2}: {median_value}')
        else:
            print(f'{header2} is not a numeric column.')


def median3():
    for header3 in headers3:
        if pd.api.types.is_numeric_dtype(df3[header3]):
            median_value = df3[header3].median()
            print(f'median of {header3}: {median_value}')
        else:
            print(f'{header3} is not a numeric column.')
print(f'{median1()} {median2()} {median3()}')

Timestamp is not a numeric column.
Median of GHI: 1.8
Median of DNI: -0.1
Median of DHI: 1.6
Median of ModA: 4.5
Median of ModB: 4.3
Median of Tamb: 28.0
Median of RH: 55.1
Median of WS: 1.9
Median of WSgust: 2.6
Median of WSstdev: 0.5
Median of WD: 181.0
Median of WDstdev: 8.6
Median of BP: 994.0
Median of Cleaning: 0.0
Median of Precipitation: 0.0
Median of TModA: 30.0
Median of TModB: 28.9
Median of Comments: 0.0
Timestamp is not a numeric column.
median of GHI: 2.1
median of DNI: 0.0
median of DHI: 2.5
median of ModA: 4.4
median of ModB: 4.3
median of Tamb: 27.2
median of RH: 59.3
median of WS: 2.2
median of WSgust: 2.9
median of WSstdev: 0.5
median of WD: 199.1
median of WDstdev: 10.8
median of BP: 976.0
median of Cleaning: 0.0
median of Precipitation: 0.0
median of TModA: 28.4
median of TModB: 28.4
median of Comments: 0.0
Timestamp is not a numeric column.
median of GHI: 0.3
median of DNI: -0.1
median of DHI: -0.1
median of ModA: 3.6
median of ModB: 3.4
median of Tamb: 25.3
median of RH: 85.4
median of WS: 0.8
median of WSgust: 1.6
median of WSstdev: 0.4
median of WD: 161.5
median of WDstdev: 6.2
median of BP: 1000.0
median of Cleaning: 0.0
median of Precipitation: 0.0
median of TModA: 26.6
median of TModB: 26.9
median of Comments: 0.0
None None None

In [63]:
headers1 = df1.columns
headers2 = df2.columns
headers3 = df3.columns

def std1():
    for header1 in headers1:
        if pd.api.types.is_numeric_dtype(df1[header1]):
            std_value = df1[header1].std()
            print(f'Standard divation of {header1}: {std_value}')
        else:
            print(f'{header1} is not a numeric column.')

def std2():
    for header2 in headers2:
        if pd.api.types.is_numeric_dtype(df2[header2]):
            std_value = df2[header2].std()
            print(f'Standard divation of {header2}: {std_value}')
        else:
            print(f'{header2} is not a numeric column.')


def std3():
    for header3 in headers3:
        if pd.api.types.is_numeric_dtype(df3[header3]):
            std_value = df3[header3].std()
            print(f'Standard divation of {header3}: {std_value}')
        else:
            print(f'{header3} is not a numeric column.')
print(f'{std1()} {std2()} {std3()}')

Timestamp is not a numeric column.
Median of GHI: 331.13132727519655
Median of DNI: 261.7105006198377
Median of DHI: 158.69107385933233
Median of ModA: 326.89485851507413
Median of ModB: 316.53651537980164
Median of Tamb: 5.924296981332788
Median of RH: 28.073068781205844
Median of WS: 1.6034658845357102
Median of WSgust: 2.029119651774774
Median of WSstdev: 0.2733946213736333
Median of WD: 102.33284204706163
Median of WDstdev: 6.385864053158973
Median of BP: 2.474993197988568
Median of Cleaning: 0.030362892221282408
Median of Precipitation: 0.03711520540633969
Median of TModA: 14.807257528633412
Median of TModB: 12.348743384105228
Median of Comments: 0.0
Timestamp is not a numeric column.
median of GHI: 322.53234661152936
median of DNI: 250.9569616573671
median of DHI: 156.52071366117195
median of ModA: 317.3469382524454
median of ModB: 307.9325104175355
median of Tamb: 4.758022740618851
median of RH: 28.778732322296694
median of WS: 1.462667670344068
median of WSgust: 1.882564525208805
median of WSstdev: 0.268923061732855
median of WD: 91.87721656228369
median of WDstdev: 5.915489536764592
median of BP: 2.153977480335337
median of Cleaning: 0.023115844854792233
median of Precipitation: 0.02635003158140825
median of TModA: 10.99833354593578
median of TModB: 12.76927711913104
median of Comments: 0.0
Timestamp is not a numeric column.
median of GHI: 298.4951504289856
median of DNI: 218.65265859128834
median of DHI: 158.94603196076645
median of ModA: 300.8968926212413
median of ModB: 288.8890726857755
median of Tamb: 4.398605011595131
median of RH: 20.520774562690175
median of WS: 1.2392483687506368
median of WSgust: 1.617053354438623
median of WSstdev: 0.29500006363719533
median of WD: 114.28479181237655
median of WDstdev: 7.5350931592808434
median of BP: 2.104419226069219
median of Cleaning: 0.031073817701868293
median of Precipitation: 0.047555992534041275
median of TModA: 12.434898577542754
median of TModB: 12.009161313594923
median of Comments: 0.0
None None None

In [67]:
headers1 = df1.columns
headers2 = df2.columns
headers3 = df3.columns

def var1():
    for header1 in headers1:
        if pd.api.types.is_numeric_dtype(df1[header1]):
            var_value = df1[header1].var()
            print(f'var of {header1}: {var_value}')
        else:
            print(f'{header1} is not a numeric column.')

def var2():
    for header2 in headers2:
        if pd.api.types.is_numeric_dtype(df2[header2]):
            var_value = df2[header2].var()
            print(f'var of {header2}: {var_value}')
        else:
            print(f'{header2} is not a numeric column.')


def var3():
    for header3 in headers3:
        if pd.api.types.is_numeric_dtype(df3[header3]):
            var_value = df3[header3].var()
            print(f'var of {header3}: {var_value}')
        else:
            print(f'{header3} is not a numeric column.')
print(f'{var1()} {var2()} {var3()}')

Timestamp is not a numeric column.
var of GHI: 109647.95590303333
var of DNI: 68492.38613468606
var of DHI: 25182.856922628067
var of ModA: 106860.24852359034
var of ModB: 100195.36556878741
var of Tamb: 35.09729472302879
var of RH: 788.0971907943142
var of WS: 2.5711028428698874
var of WSgust: 4.117326561218579
var of WSstdev: 0.0747446189960323
var of WD: 10472.010561428866
var of WDstdev: 40.77925970542795
var of BP: 6.125591330089681
var of Cleaning: 0.0009219052240412117
var of Precipitation: 0.0013775384723547868
var of TModA: 219.25487551927088
var of TModB: 152.49146316648265
var of Comments: 0.0
Timestamp is not a numeric column.
var of GHI: 104027.1146107397
var of DNI: 62979.39660429721
var of DHI: 24498.73380500258
var of ModA: 100709.0792182014
var of ModB: 94822.43097204564
var of Tamb: 22.638780400246127
var of RH: 828.2154340784045
var of WS: 2.139396713869743
var of WSgust: 3.5440491915746537
var of WSstdev: 0.07231961313177294
var of WD: 8441.422923232778
var of WDstdev: 34.993016459571365
var of BP: 4.639618985791768
var of Cleaning: 0.0005343422833508246
var of Precipitation: 0.0006943241643412123
var of TModA: 120.96334078765634
var of TModB: 163.05443814516352
var of Comments: 0.0
Timestamp is not a numeric column.
var of GHI: 89099.35482962272
var of DNI: 47808.985109038505
var of DHI: 25263.84107607299
var of ModA: 90538.93998911881
var of ModB: 83456.89631724729
var of Tamb: 19.3477260480298
var of RH: 421.1021886527521
var of WS: 1.5357365194511146
var of WSgust: 2.6148615511012028
var of WSstdev: 0.08702503754594929
var of WD: 13061.01363959825
var of WDstdev: 56.777628919040964
var of BP: 4.428580279049771
var of Cleaning: 0.0009655821465689433
var of Precipitation: 0.002261572425897789
var of TModA: 154.62670263377478
var of TModB: 144.21995545594496
var of Comments: 0.0
None None None